#!/bin/bash
# This scrip installs zookeeper
# More documentation on the README.md file

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "Downloading Zookeeper"

mkdir -p /opt/zookeeper

cd /opt/zookeeper

wget http://archive.apache.org/dist/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz
ln -s zookeeper-3.4.8 zookeeper
tar -xzf zookeeper-3.4.8.tar.gz
rm -rf zookeeper-3.4.8.tar.gz

PID_PATH="/var/zookeeper"

mkdir -p $PID_PATH
