#!/bin/bash
echo "Oozie setup"

install-packages zip unzip tar wget

tmp_dir=/tmp/oozie
mkdir $tmp_dir

if [ -n "$OOZIE_DOWNLOAD_URL" ]; then
   wget -P $tmp_dir $OOZIE_DOWNLOAD_URL
   OOZIE_FILE=$(basename $OOZIE_DOWNLOAD_URL)
elif [ -n "$OOZIE_FILE" ]; then
    install -D -g root -o root -m 0755 $(dirname $0)/$OOZIE_FILE $tmp_dir
fi

cd $tmp_dir
tar xzf $OOZIE_FILE
rm $OOZIE_FILE

if [ $(ls | wc -l) == "1" ]; then
  mv $(ls) /opt/oozie
else
  mkdir /opt/oozie
  mv * /opt/oozie/
fi

rm -rf tmp_dir
