#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -z "${STORM_DOWNLOAD_URL:-}" -a -z "${DIB_STORM_VERSION:-}"]; then
    echo -e "Neither DIB_STORM_VERSION nor STORM_DOWNLOAD_URL are set. Impossible to install Storm.\nAborting"
    exit 1
fi
