#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu

DISTRO=$(lsb_release -is || :)

if [ "$DISTRO" = 'CentOS' -o "$DISTRO" = 'RedHatEnterpriseServer' ]; then
    sed '/^Defaults    requiretty*/ s/^/#/' -i /etc/sudoers
fi

