#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu

DISTRO=$(lsb_release -is || :)

if [ "$DISTRO" = "Ubuntu" ]; then
    apt-get update
elif [ "$DISTRO" = 'CentOS' -o "$DISTRO" = 'RedHatEnterpriseServer' ]; then
    yum clean all && yum repolist
fi
