#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "MapR version ${DIB_MAPR_VERSION}"

if [ -z ${DIB_MAPR_VERSION} ]; then
    echo "DIB_MAPR_VERSION not set.\nExit"
    exit 1
fi
