#!/bin/bash

echo "Begin: installation of Java"
set -e

# NOTE: $(dirname $0) is read-only, use space under $TARGET_ROOT
JAVA_HOME=$TARGET_ROOT/usr/java
mkdir -p $JAVA_HOME

if [ -n "$JAVA_DOWNLOAD_URL" ]; then
   install-packages wget
   JAVA_FILE=$(basename $JAVA_DOWNLOAD_URL)
   wget --no-check-certificate --no-cookies \
       --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
       -O $JAVA_HOME/$JAVA_FILE $JAVA_DOWNLOAD_URL
   if [ $? -eq 0 ]; then
      echo "Java download successful"
   else
      echo "Error downloading $JAVA_DOWNLOAD_URL, exiting"
      exit 1
   fi
elif [ -n "$JAVA_FILE" ]; then
   install -D -g root -o root -m 0755 $(dirname $0)/$JAVA_FILE $JAVA_HOME
fi

if [ -z "$JAVA_FILE" ]; then
   install-packages default-jre
else
   cd $JAVA_HOME
   if [[ $JAVA_FILE == *.tar.gz ]]; then
      echo -e "\n" | tar -zxvf $JAVA_FILE
   elif [[ $JAVA_FILE == *.bin ]]; then
      echo -e "\n" | sh $JAVA_FILE
   else
      echo "Unknown file type: $JAVA_FILE, exiting"
      exit 1
   fi
   rm $JAVA_FILE
fi

echo "End: installation of Java"
