#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -e

echo "Installing OpenJDK"

case "$DISTRO_NAME" in
    ubuntu )
        install-packages openjdk-7-jdk
        JAVA_PATH=$(update-alternatives --list java)
        JAVA_HOME=${JAVA_PATH%/bin/java}
    ;;
    fedora | rhel | centos )
        install-packages java-1.7.0-openjdk-devel
        JAVA_HOME=$(rpm -E "%{java_home}")
    ;;
esac

echo "JAVA_HOME=$JAVA_HOME" >> $TARGET_ROOT/etc/environment

echo "OpenJDK has been installed"
