#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "Installing OpenJDK"

case "$DISTRO_NAME" in
    ubuntu )
        JRE_PATH=$(update-alternatives --list java)
        JRE_HOME=${JRE_PATH%/bin/java}
        JDK_PATH=$(update-alternatives --list javac)
        JDK_HOME=${JDK_PATH%/bin/javac}
    ;;
    fedora | rhel | centos )
        # NOTE: rpm -E "%{java_home}" command returns wrong java home
        # on CentOS, Fedora and RHEL
        JRE_HOME="/usr/lib/jvm/java-openjdk"
        JDK_HOME="$JRE_HOME"
    ;;
esac

setup-java-home $JRE_HOME $JDK_HOME

echo "OpenJDK has been installed"
