#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DISTRO_NAME" in
    fedora | rhel7 | centos7 )
        mkdir -p /etc/mysql/conf.d
    ;;
esac

rm -rf /var/lib/mysql/ib_logfile*
