#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -e

if [ "$DISTRO_NAME" = "fedora" ]; then
    install-packages community-mysql community-mysql-libs community-mysql-server mysql-connector-java
    mkdir -p /etc/mysql/conf.d
elif [ "$DISTRO_NAME" = "rhel" -o "$DISTRO_NAME" = "centos" ]; then
    install-packages mysql mysql-libs mysql-server mysql-connector-java
    mkdir -p /etc/mysql/conf.d
elif [ "$DISTRO_NAME" = "ubuntu" ]; then
    install-packages mysql-server-5.5 mysql-client-5.5 libmysql-java
else
    echo "Unknown distribution"
    exit 1
fi

rm -rf /var/lib/mysql/ib_logfile*
