#!/bin/bash
set -e
source $_LIB/die
if [ -z "$JAVA_DOWNLOAD_URL" ]; then
   [ -n "$JAVA_FILE" ] || die "JAVA_FILE and JAVA_DOWNLOAD_URL are not set. Impossible to install java. Exit"
fi
[ -n "$DIB_HADOOP_VERSION" ] || die "DIB_HADOOP_VERSION is not set. Impossible to install hadoop. Exit"

version_check=$(echo $DIB_HADOOP_VERSION | sed -e '/[0-9]\.[0-9]\.[0-9]/d')
if [[ -z $version_check ]]; then
   echo "All variables are set, continue."
else
   echo "Version error. Exit"
   exit 1
fi

