#!/bin/bash

set -e

distro=$(lsb_release -is)

if [ "$distro" = "Fedora" ]; then
    install-packages iptables-services
fi

if which service; then
    service ip6tables save
    chkconfig ip6tables off
fi
