#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -e

distro=$(lsb_release -is)

if [ "$distro" = "Fedora" ]; then
    install-packages iptables-services
fi

if which service; then
    service ip6tables save
    chkconfig ip6tables off
fi
