#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ "$DISTRO_NAME" = "fedora" ]; then
    install-packages iptables-services
fi

if which service; then
    service iptables save
    chkconfig iptables off
fi
