#!/bin/bash
tmp_dir=/tmp/hadoop
mkdir -p $TARGET_ROOT/$tmp_dir
echo "Installing SSH server"

mkdir /root/.ssh
install-packages openssh-server

echo "Creating hadoop user & group"

addgroup hadoop
adduser --ingroup hadoop --disabled-password --gecos GECOS hadoop
adduser hadoop sudo

echo "Hadoop version $DIB_HADOOP_VERSION will be injected into image. Starting the download"

wget -P $tmp_dir "http://archive.apache.org/dist/hadoop/core/hadoop-"$DIB_HADOOP_VERSION"/hadoop_"$DIB_HADOOP_VERSION"-1_x86_64.deb"
if [ $? -ne 0 ]; then
   echo -e "Could not find Hadoop version $DIB_HADOOP_VERSION.\nExit"
   exit 1
fi

echo "Installing Hadoop"

dpkg -i $tmp_dir/hadoop_$DIB_HADOOP_VERSION-1_x86_64.deb
rm $tmp_dir/hadoop_$DIB_HADOOP_VERSION-1_x86_64.deb

echo "Pre-configuring Hadoop"

filename=$(find $TARGET_ROOT/usr/lib/ -maxdepth 1 -name "jdk*")
echo -e "HADOOP_HOME=/usr/share/hadoop/\nPATH=\$PATH:/usr/sbin/" >> $TARGET_ROOT/home/hadoop/.bashrc
echo -e "JAVA_HOME=$filename\nPATH=\$PATH:$filename/bin/" >> $TARGET_ROOT/home/hadoop/.bashrc
sed -i "s,export JAVA_HOME=.*,export JAVA_HOME=$filename," /etc/hadoop/hadoop-env.sh
log_dir=/mnt/log/hadoop/\$USER/
sed -i "s,export HADOOP_LOG_DIR=.*,export HADOOP_LOG_DIR=$log_dir," /etc/hadoop/hadoop-env.sh
log_dir=/mnt/log/hadoop/hdfs
sed -i "s,export HADOOP_SECURE_DN_LOG_DIR=.*,export HADOOP_SECURE_DN_LOG_DIR=$log_dir," /etc/hadoop/hadoop-env.sh
