#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail
DIB_UNLIMITED_SECURITY_LOCATION="${DIB_UNLIMITED_SECURITY_LOCATION:-https://tarballs.openstack.org/sahara-extra/dist/common-artifacts/}"

mkdir /tmp/UnlimitedPolicy/
wget $DIB_UNLIMITED_SECURITY_LOCATION/local_policy.jar -O /tmp/UnlimitedPolicy/local_policy.jar
wget $DIB_UNLIMITED_SECURITY_LOCATION/US_export_policy.jar -O /tmp/UnlimitedPolicy/US_export_policy.jar
