#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -z "$SAHARA_ELEMENTS_COMMIT_ID" -o -z "$DIB_UTILS_COMMIT_ID" -o -z "$DIB_COMMIT_ID" ]; then
    echo "SAHARA_ELEMENTS_COMMIT_ID, DIB_UTILS_COMMIT_ID and DIB_COMMIT_ID must be specified, exiting"
    exit 3
else
    echo -e "Sahara-elements-extra commit id: $SAHARA_ELEMENTS_COMMIT_ID,
dib-utils commit id: $DIB_UTILS_COMMIT_ID,
Diskimage-builder commit id: $DIB_COMMIT_ID" > /etc/sahara-extra.version
fi
