#!/bin/bash
chown root:root /mnt
mkdir -p /mnt/log/hadoop
chown hadoop:hadoop /mnt/log/hadoop
mkdir /var/run/hadoop
mkdir /run/hadoop
chown hadoop:hadoop /var/run/hadoop/
chown hadoop:hadoop /run/hadoop/
echo "Setup ubuntu's directory"
mkdir -p /home/ubuntu/.ssh
touch /home/ubuntu/.ssh/authorized_keys
chown -R ubuntu:ubuntu /home/ubuntu
