#!/bin/bash
distro=$(lsb_release -is || :)
case "$distro" in
   Ubuntu )
      mkdir /run/hadoop
      chown hadoop:hadoop /run/hadoop/
      mkdir -p /home/ubuntu/.ssh
      touch /home/ubuntu/.ssh/authorized_keys
      chown -R ubuntu:ubuntu /home/ubuntu
   ;;
   Fedora )
      sleep 20
      rm /etc/resolv.conf
      service network restart
      if [ $(lsb_release -rs) = '19' ]; then
         chown -R fedora:fedora /etc/hadoop
         chown -R fedora:fedora /home/fedora
      else
         chown -R ec2-user:ec2-user /home/ec2-user
         chown -R ec2-user:ec2-user /etc/hadoop
      fi
      #TODO: configure iptables (https://bugs.launchpad.net/savanna/+bug/1195744)
      iptables -F
   ;;
   * )
      echo "Unknown distro: $distro. Exiting."
      exit 1
   ;;
esac

# Common
chown root:root /mnt
mkdir -p /var/run/hadoop ; chown hadoop:hadoop /var/run/hadoop
mkdir -p /mnt/log/hadoop ; chown hadoop:hadoop /mnt/log/hadoop
