#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

tmp_dir=$TARGET_ROOT/tmp/spark
mkdir -p $tmp_dir

# The user is not providing his own Spark distribution package
if [ -z "${SPARK_DOWNLOAD_URL:-}" ]; then
    # Check hadoop version
    # INFO on hadoop versions: http://spark.apache.org/docs/latest/hadoop-third-party-distributions.html
    if [ -z "${DIB_SPARK_VERSION:-}" ]; then
        case "$DIB_HADOOP_VERSION" in
            CDH4)
                DIB_SPARK_VERSION=1.0.0
                SPARK_HADOOP_DL=cdh4
                ;;
            *)
                echo -e "WARNING: Hadoop version $DIB_HADOOP_VERSION not supported."
                echo -e "WARNING: make sure SPARK_DOWNLOAD_URL points to a compatible Spark version."
                ;;
        esac
    fi

    SPARK_DOWNLOAD_URL="http://archive.apache.org/dist/spark/spark-$DIB_SPARK_VERSION/spark-$DIB_SPARK_VERSION-bin-$SPARK_HADOOP_DL.tgz"
fi

echo "Downloading SPARK"
spark_file=$(basename "$SPARK_DOWNLOAD_URL")
cached_tar="$DIB_IMAGE_CACHE/$spark_file"
$TMP_HOOKS_PATH/bin/cache-url $SPARK_DOWNLOAD_URL $cached_tar
sudo install -D -g root -o root -m 0755 $cached_tar $tmp_dir
