#!/bin/bash

set -eux

if [ $(lsb_release -is) = 'Ubuntu' ]; then
    export DEBIAN_FRONTEND=noninteractive
    export RUNLEVEL=1
fi

install-packages \
    cloudera-manager-agent \
    cloudera-manager-daemons \
    cloudera-manager-server \
    cloudera-manager-server-db-2 \
    hadoop-hdfs-datanode \
    hadoop-hdfs-namenode \
    hadoop-hdfs-secondarynamenode \
    hadoop-mapreduce \
    hadoop-mapreduce-historyserver \
    hadoop-yarn-nodemanager \
    hadoop-yarn-resourcemanager \
    hbase \
    hive-hcatalog \
    hive-metastore \
    hive-server2 \
    hive-webhcat-server \
    hue \
    ntp \
    oozie \
    oracle-j2sdk1.7 \
    spark-core \
    zookeeper

if [ $DIB_CDH_VERSION != "5.0" ]; then
    # CDH5.0 does not have below packages.
    install-packages \
        flume-ng \
        hbase-solr \
        impala \
        impala-server \
        impala-state-store \
        impala-catalog \
        impala-shell \
        sentry \
        solr-server \
        spark-history-server \
        sqoop2
fi

if [ $(lsb_release -is) = 'Ubuntu' ]; then
    unset RUNLEVEL
fi
