#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -e

install-packages wget unzip

OOZIE_WEBAPP_DIRECTORY="/var/lib/oozie"
EXTJS_FILENAME=$(basename $EXTJS_DOWNLOAD_URL)
pushd $OOZIE_WEBAPP_DIRECTORY
wget "$EXTJS_DOWNLOAD_URL"
unzip $EXTJS_FILENAME
popd
