#!/bin/bash

mv /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/tempfile
cat >> /etc/yum.repos.d/fedora.repo <<EOF
[Local-Repository]
name=Fedora \$releasever - \$basearch - Local
baseurl=$FEDORA_MIRROR
enabled=1
gpgcheck=0
priority=1
EOF
yum makecache
