#!/bin/bash

# Copyright (c) 2013 Hortonworks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##########################################################
# Element install script for turning off iptables (and ip6tables)
# once the HDP install has completed.
#
# This is a recommended network optimization for images used
# by Sahara and OpenStack.
##########################################################


# Turn off iptables
/etc/init.d/iptables save
/etc/init.d/iptables stop
chkconfig iptables off
chkconfig ip6tables off
