#!/bin/bash

# Copyright (c) 2013 Hortonworks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##########################################################
# Element install script for turning off the Hadoop 2
#  and yarn services, once the HDP install has completed.
#
##########################################################

# Turn off these hadoop services at first boot, since
#  Ambari will configure the environment before the Hadoop
#  cluster is started.

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# This is only necessary for an HDP 2.x install
if [[ $DIB_HDP_VERSION == "2.0"  ]]; then
    chkconfig hadoop-mapreduce-historyserver off
    chkconfig hadoop-yarn-nodemanager off
    chkconfig hadoop-yarn-proxyserver off
    chkconfig hadoop-yarn-resourcemanager off
fi

