#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

ln -s /usr/share/java/mysql-connector-java.jar /opt/oozie/libtools/mysql.jar
if [ "$DIB_HADOOP_VERSION" = "3.0.1" ]; then
    ln -s /usr/share/java/mysql-connector-java.jar /opt/oozie/embedded-oozie-server/dependency/mysql.jar
    /opt/oozie/bin/oozie-setup.sh  -d /opt/oozie/libtools
else
    ln -s /usr/share/java/mysql-connector-java.jar /opt/oozie/oozie-server/lib/mysql.jar
    /opt/oozie/bin/oozie-setup.sh prepare-war -d /opt/oozie/libtools
fi

chown -R hadoop:hadoop /opt/oozie
