#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "${DISTRO_NAME}" in
    centos | centos7 | rhel | fedora )
        export DIB_DEFAULT_APACHE_DIR="/var/www/html"
    ;;
    ubuntu )
        export DIB_DEFAULT_APACHE_DIR="/var/www"
    ;;
    * )
        echo "Unsupported distro: ${DISTRO_NAME}"
        exit 1
    ;;
esac
