#!/bin/bash

# Copyright (c) 2013 Hortonworks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##########################################################
# Element Script for configuring nozeroconf in HDP Install
#
# This setting is necessary to disable the routing rule that is otherwise injected into the image
# Routing rule prevents cloud-init from contacting meta data service on quantum
# See: https://bugzilla.redhat.com/show_bug.cgi?id=983611

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "NOZEROCONF=yes" >> /etc/sysconfig/network
