#!/bin/bash
echo "Java setup begins"
set -e

# NOTE: $(dirname $0) is read-only, use space under $TARGET_ROOT
JAVA_HOME=$TARGET_ROOT/usr/java
mkdir -p $JAVA_HOME

if [ -n "$JAVA_DOWNLOAD_URL" ]; then
   install-packages wget
   wget --no-cookies --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com" -P $JAVA_HOME $JAVA_DOWNLOAD_URL
   if [ $? -eq 0 ]; then
      echo "Java downloaded"
   else
      echo "Error downloading java. Exiting."
      exit 1
   fi
   JAVA_FILE=$(basename $JAVA_DOWNLOAD_URL)
elif [ -n "$JAVA_FILE" ]; then
   install -D -g root -o root -m 0755 $(dirname $0)/$JAVA_FILE $JAVA_HOME
fi

cd $JAVA_HOME
if echo $JAVA_FILE | grep -q -s -F .tar.gz ; then
   echo -e "\n" | tar -zxvf $JAVA_FILE
elif echo $JAVA_FILE | grep -q -s -F .bin ; then
   echo -e "\n" | sh $JAVA_FILE
else
   echo "Unknown file type: $JAVA_FILE. Exiting."
   exit 1
fi
rm $JAVA_FILE

echo "Java was installed"
