#!/bin/bash

distro=$(lsb_release -is || :)
case "$distro" in
   Ubuntu )
      mkdir /run/hadoop
      chown hadoop:hadoop /run/hadoop/
      mkdir -p /home/ubuntu/.ssh
      touch /home/ubuntu/.ssh/authorized_keys
      chown -R ubuntu:ubuntu /home/ubuntu
      chown -R ubuntu:ubuntu /etc/hadoop
   ;;
   * )
      echo "Unknown distro: $distro. Exiting."
      exit 1
   ;;
esac

# Common
chown root:root /mnt
mkdir -p /var/run/hadoop ; chown hadoop:hadoop /var/run/hadoop
mkdir -p /mnt/log/hadoop ; chown hadoop:hadoop /mnt/log/hadoop

# Clean
if [ "$distro" == "Ubuntu" ]; then
  if [ -f /etc/rc.local.old ]; then
    mv /etc/rc.local.old /etc/rc.local
  fi
fi

exit 0
