#!/bin/bash
set -e

if [ -z "$OOZIE_DOWNLOAD_URL" ]; then
   if [ -z "$OOZIE_FILE" ]; then
      echo "OOZIE_FILE and OOZIE_DOWNLOAD_URL are not set. Impossible to install Oozie. Exit"
      exit 1
   fi
fi
